# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'BullsEye' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BullsEye
  pod 'Alamofire', '~> 4.7'

  target 'Tests' do
    inherit! :search_paths
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.3'
  end

end
